apiVersion: apps/v1
kind: Deployment

metadata:
  name: "goserver"
  labels: 
    app: "goserver"

spec:
  selector: 
    matchLabels:
      app: "goserver"
  replicas: 3
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "liverdayg/hello-golang:v2"
          env:
            - name: NAME
              value: "Vitor Medeiro"
            - name: AGE
              value: "24"